// Capital + 4 real cities of each province (checked against https://apis.datos.gob.ar/georef/api/localidades).
export const provinces = [
  { province: 'Buenos Aires', capital: 'La Plata', cities: ['Mar del Plata','Bahía Blanca','Tandil','Junín'] },
  { province: 'Catamarca', capital: 'San Fernando del Valle de Catamarca', cities: ['Belén','Andalgalá','Tinogasta','Santa María'] },
  { province: 'Chaco', capital: 'Resistencia', cities: ['Presidencia Roque Sáenz Peña','Villa Ángela','Charata','General José de San Martín'] },
  { province: 'Chubut', capital: 'Rawson', cities: ['Comodoro Rivadavia','Trelew','Puerto Madryn','Esquel'] },
  { province: 'Córdoba', capital: 'Córdoba', cities: ['Río Cuarto','Villa María','San Francisco','Villa Carlos Paz'] },
  { province: 'Corrientes', capital: 'Corrientes', cities: ['Goya','Paso de los Libres','Curuzú Cuatiá','Mercedes'] },
  { province: 'Entre Ríos', capital: 'Paraná', cities: ['Concordia','Gualeguaychú','Concepción del Uruguay','Victoria'] },
  { province: 'Formosa', capital: 'Formosa', cities: ['Clorinda','Pirané','El Colorado','Las Lomitas'] },
  { province: 'Jujuy', capital: 'San Salvador de Jujuy', cities: ['San Pedro','Libertador General San Martín','Palpalá','Humahuaca'] },
  { province: 'La Pampa', capital: 'Santa Rosa', cities: ['General Pico','General Acha','Realicó','Eduardo Castex'] },
  { province: 'La Rioja', capital: 'La Rioja', cities: ['Chilecito','Aimogasta','Chamical','Chepes'] },
  { province: 'Mendoza', capital: 'Mendoza', cities: ['San Rafael','Godoy Cruz','Malargüe','San Martín'] },
  { province: 'Misiones', capital: 'Posadas', cities: ['Oberá','Eldorado','Puerto Iguazú','Apóstoles'] },
  { province: 'Neuquén', capital: 'Neuquén', cities: ['Cutral Có','Zapala','San Martín de los Andes','Plottier'] },
  { province: 'Río Negro', capital: 'Viedma', cities: ['San Carlos de Bariloche','General Roca','Cipolletti','Villa Regina'] },
  { province: 'Salta', capital: 'Salta', cities: ['San Ramón de la Nueva Orán','Tartagal','Cafayate','San José de Metán'] },
  { province: 'San Juan', capital: 'San Juan', cities: ['Caucete','San José de Jáchal','Chimbas','Villa Aberastain'] },
  { province: 'San Luis', capital: 'San Luis', cities: ['Villa Mercedes','Merlo','Justo Daract','La Punta'] },
  { province: 'Santa Cruz', capital: 'Río Gallegos', cities: ['Caleta Olivia','El Calafate','Puerto Deseado','Pico Truncado'] },
  { province: 'Santa Fe', capital: 'Santa Fe', cities: ['Rosario','Rafaela','Reconquista','Venado Tuerto'] },
  { province: 'Santiago del Estero', capital: 'Santiago del Estero', cities: ['La Banda','Termas de Río Hondo','Añatuya','Frías'] },
  { province: 'Tierra del Fuego', capital: 'Ushuaia', cities: ['Río Grande','Tolhuin','Puerto Argentino','Laguna Escondida'] },
  { province: 'Tucumán', capital: 'San Miguel de Tucumán', cities: ['Concepción','Tafí Viejo','Monteros','Aguilares'] },
];
