export const provinces = [
  {
    province: 'Buenos Aires',
    options: [
      { name: 'La Plata', correct: true, difficulty: 1 },
      { name: 'Mar del Plata', correct: false, difficulty: 1 },
      { name: 'Bahía Blanca', correct: false, difficulty: 1 },
      { name: 'Quilmes', correct: false, difficulty: 1 },
      { name: 'Córdoba', correct: false, difficulty: 2 },
      { name: 'Mendoza', correct: false, difficulty: 2 },
      { name: 'San Miguel de Tucumán', correct: false, difficulty: 2 },
      { name: 'La Plata del Oeste', correct: false, difficulty: 3 },
      { name: 'La Plata del Este', correct: false, difficulty: 3 },
      { name: 'La Plata del Sur', correct: false, difficulty: 3 },
      { name: 'La Plata del Norte', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'Catamarca',
    options: [
      { name: 'San Fernando del Valle de Catamarca', correct: true, difficulty: 1 },
      { name: 'Belén', correct: false, difficulty: 1 },
      { name: 'Andalgalá', correct: false, difficulty: 1 },
      { name: 'Tinogasta', correct: false, difficulty: 1 },
      { name: 'La Rioja', correct: false, difficulty: 2 },
      { name: 'Santiago del Estero', correct: false, difficulty: 2 },
      { name: 'San Salvador de Jujuy', correct: false, difficulty: 2 },
      { name: 'San Fernando de Catamarca', correct: false, difficulty: 3 },
      { name: 'San Fernando del Valle', correct: false, difficulty: 3 },
      { name: 'Valle de Catamarca', correct: false, difficulty: 3 },
      { name: 'San Fernando de Valle Catamarca', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'Chaco',
    options: [
      { name: 'Resistencia', correct: true, difficulty: 1 },
      { name: 'Barranqueras', correct: false, difficulty: 1 },
      { name: 'Presidencia Roque Sáenz Peña', correct: false, difficulty: 1 },
      { name: 'Villa Ángela', correct: false, difficulty: 1 },
      { name: 'Formosa', correct: false, difficulty: 2 },
      { name: 'Corrientes', correct: false, difficulty: 2 },
      { name: 'Posadas', correct: false, difficulty: 2 },
      { name: 'Resistencia del Norte', correct: false, difficulty: 3 },
      { name: 'Resistencia del Sur', correct: false, difficulty: 3 },
      { name: 'Nueva Resistencia', correct: false, difficulty: 3 },
      { name: 'Resistencia Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'Chubut',
    options: [
      { name: 'Rawson', correct: true, difficulty: 1 },
      { name: 'Trelew', correct: false, difficulty: 1 },
      { name: 'Puerto Madryn', correct: false, difficulty: 1 },
      { name: 'Comodoro Rivadavia', correct: false, difficulty: 1 },
      { name: 'Viedma', correct: false, difficulty: 2 },
      { name: 'Ushuaia', correct: false, difficulty: 2 },
      { name: 'Santa Rosa', correct: false, difficulty: 2 },
      { name: 'Rawson del Este', correct: false, difficulty: 3 },
      { name: 'Rawson del Oeste', correct: false, difficulty: 3 },
      { name: 'Nuevo Rawson', correct: false, difficulty: 3 },
      { name: 'Rawson Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'Córdoba',
    options: [
      { name: 'Córdoba', correct: true, difficulty: 1 },
      { name: 'Río Cuarto', correct: false, difficulty: 1 },
      { name: 'Villa María', correct: false, difficulty: 1 },
      { name: 'Alta Gracia', correct: false, difficulty: 1 },
      { name: 'Santa Fe', correct: false, difficulty: 2 },
      { name: 'San Luis', correct: false, difficulty: 2 },
      { name: 'La Rioja', correct: false, difficulty: 2 },
      { name: 'Córdoba del Norte', correct: false, difficulty: 3 },
      { name: 'Córdoba del Sur', correct: false, difficulty: 3 },
      { name: 'Nueva Córdoba', correct: false, difficulty: 3 },
      { name: 'Córdoba Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'Corrientes',
    options: [
      { name: 'Corrientes', correct: true, difficulty: 1 },
      { name: 'Goya', correct: false, difficulty: 1 },
      { name: 'Mercedes', correct: false, difficulty: 1 },
      { name: 'Curuzú Cuatiá', correct: false, difficulty: 1 },
      { name: 'Resistencia', correct: false, difficulty: 2 },
      { name: 'Posadas', correct: false, difficulty: 2 },
      { name: 'Formosa', correct: false, difficulty: 2 },
      { name: 'Corrientes del Este', correct: false, difficulty: 3 },
      { name: 'Corrientes del Oeste', correct: false, difficulty: 3 },
      { name: 'Nueva Corrientes', correct: false, difficulty: 3 },
      { name: 'Corrientes Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'Entre Ríos',
    options: [
      { name: 'Paraná', correct: true, difficulty: 1 },
      { name: 'Concordia', correct: false, difficulty: 1 },
      { name: 'Gualeguaychú', correct: false, difficulty: 1 },
      { name: 'Concepción del Uruguay', correct: false, difficulty: 1 },
      { name: 'Santa Fe', correct: false, difficulty: 2 },
      { name: 'Corrientes', correct: false, difficulty: 2 },
      { name: 'La Plata', correct: false, difficulty: 2 },
      { name: 'Paraná del Norte', correct: false, difficulty: 3 },
      { name: 'Paraná del Sur', correct: false, difficulty: 3 },
      { name: 'Nuevo Paraná', correct: false, difficulty: 3 },
      { name: 'Paraná Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'Formosa',
    options: [
      { name: 'Formosa', correct: true, difficulty: 1 },
      { name: 'Clorinda', correct: false, difficulty: 1 },
      { name: 'Pirané', correct: false, difficulty: 1 },
      { name: 'Las Lomitas', correct: false, difficulty: 1 },
      { name: 'Resistencia', correct: false, difficulty: 2 },
      { name: 'Corrientes', correct: false, difficulty: 2 },
      { name: 'Posadas', correct: false, difficulty: 2 },
      { name: 'Formosa del Norte', correct: false, difficulty: 3 },
      { name: 'Formosa del Sur', correct: false, difficulty: 3 },
      { name: 'Nueva Formosa', correct: false, difficulty: 3 },
      { name: 'Formosa Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'Jujuy',
    options: [
      { name: 'San Salvador de Jujuy', correct: true, difficulty: 1 },
      { name: 'Palpalá', correct: false, difficulty: 1 },
      { name: 'San Pedro de Jujuy', correct: false, difficulty: 1 },
      { name: 'Libertador General San Martín', correct: false, difficulty: 1 },
      { name: 'Salta', correct: false, difficulty: 2 },
      { name: 'San Miguel de Tucumán', correct: false, difficulty: 2 },
      { name: 'Santiago del Estero', correct: false, difficulty: 2 },
      { name: 'San Salvador de Jujuy del Norte', correct: false, difficulty: 3 },
      { name: 'San Salvador de Jujuy del Sur', correct: false, difficulty: 3 },
      { name: 'Nuevo San Salvador de Jujuy', correct: false, difficulty: 3 },
      { name: 'San Salvador de Jujuy Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'La Pampa',
    options: [
      { name: 'Santa Rosa', correct: true, difficulty: 1 },
      { name: 'General Pico', correct: false, difficulty: 1 },
      { name: 'Toay', correct: false, difficulty: 1 },
      { name: 'General Acha', correct: false, difficulty: 1 },
      { name: 'Neuquén', correct: false, difficulty: 2 },
      { name: 'Viedma', correct: false, difficulty: 2 },
      { name: 'Bahía Blanca', correct: false, difficulty: 2 },
      { name: 'Santa Rosa del Norte', correct: false, difficulty: 3 },
      { name: 'Santa Rosa del Sur', correct: false, difficulty: 3 },
      { name: 'Nueva Santa Rosa', correct: false, difficulty: 3 },
      { name: 'Santa Rosa Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'La Rioja',
    options: [
      { name: 'La Rioja', correct: true, difficulty: 1 },
      { name: 'Chilecito', correct: false, difficulty: 1 },
      { name: 'Chamical', correct: false, difficulty: 1 },
      { name: 'Aimogasta', correct: false, difficulty: 1 },
      { name: 'San Juan', correct: false, difficulty: 2 },
      { name: 'Catamarca', correct: false, difficulty: 2 },
      { name: 'San Fernando del Valle de Catamarca', correct: false, difficulty: 2 },
      { name: 'La Rioja del Norte', correct: false, difficulty: 3 },
      { name: 'La Rioja del Sur', correct: false, difficulty: 3 },
      { name: 'Nueva La Rioja', correct: false, difficulty: 3 },
      { name: 'La Rioja Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'Mendoza',
    options: [
      { name: 'Mendoza', correct: true, difficulty: 1 },
      { name: 'San Rafael', correct: false, difficulty: 1 },
      { name: 'Godoy Cruz', correct: false, difficulty: 1 },
      { name: 'Maipú', correct: false, difficulty: 1 },
      { name: 'San Juan', correct: false, difficulty: 2 },
      { name: 'San Luis', correct: false, difficulty: 2 },
      { name: 'Córdoba', correct: false, difficulty: 2 },
      { name: 'Mendoza del Norte', correct: false, difficulty: 3 },
      { name: 'Mendoza del Sur', correct: false, difficulty: 3 },
      { name: 'Nueva Mendoza', correct: false, difficulty: 3 },
      { name: 'Mendoza Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'Misiones',
    options: [
      { name: 'Posadas', correct: true, difficulty: 1 },
      { name: 'Oberá', correct: false, difficulty: 1 },
      { name: 'Eldorado', correct: false, difficulty: 1 },
      { name: 'Puerto Iguazú', correct: false, difficulty: 1 },
      { name: 'Corrientes', correct: false, difficulty: 2 },
      { name: 'Resistencia', correct: false, difficulty: 2 },
      { name: 'Formosa', correct: false, difficulty: 2 },
      { name: 'Posadas del Norte', correct: false, difficulty: 3 },
      { name: 'Posadas del Sur', correct: false, difficulty: 3 },
      { name: 'Nueva Posadas', correct: false, difficulty: 3 },
      { name: 'Posadas Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'Neuquén',
    options: [
      { name: 'Neuquén', correct: true, difficulty: 1 },
      { name: 'Cutral Có', correct: false, difficulty: 1 },
      { name: 'Zapala', correct: false, difficulty: 1 },
      { name: 'San Martín de los Andes', correct: false, difficulty: 1 },
      { name: 'Viedma', correct: false, difficulty: 2 },
      { name: 'Santa Rosa', correct: false, difficulty: 2 },
      { name: 'Río Gallegos', correct: false, difficulty: 2 },
      { name: 'Neuquén del Norte', correct: false, difficulty: 3 },
      { name: 'Neuquén del Sur', correct: false, difficulty: 3 },
      { name: 'Nuevo Neuquén', correct: false, difficulty: 3 },
      { name: 'Neuquén Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'Río Negro',
    options: [
      { name: 'Viedma', correct: true, difficulty: 1 },
      { name: 'General Roca', correct: false, difficulty: 1 },
      { name: 'San Carlos de Bariloche', correct: false, difficulty: 1 },
      { name: 'Cipolletti', correct: false, difficulty: 1 },
      { name: 'Neuquén', correct: false, difficulty: 2 },
      { name: 'Rawson', correct: false, difficulty: 2 },
      { name: 'Santa Rosa', correct: false, difficulty: 2 },
      { name: 'Viedma del Norte', correct: false, difficulty: 3 },
      { name: 'Viedma del Sur', correct: false, difficulty: 3 },
      { name: 'Nueva Viedma', correct: false, difficulty: 3 },
      { name: 'Viedma Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'Salta',
    options: [
      { name: 'Salta', correct: true, difficulty: 1 },
      { name: 'San Ramón de la Nueva Orán', correct: false, difficulty: 1 },
      { name: 'Tartagal', correct: false, difficulty: 1 },
      { name: 'Cafayate', correct: false, difficulty: 1 },
      { name: 'San Salvador de Jujuy', correct: false, difficulty: 2 },
      { name: 'San Miguel de Tucumán', correct: false, difficulty: 2 },
      { name: 'Santiago del Estero', correct: false, difficulty: 2 },
      { name: 'Salta del Norte', correct: false, difficulty: 3 },
      { name: 'Salta del Sur', correct: false, difficulty: 3 },
      { name: 'Nueva Salta', correct: false, difficulty: 3 },
      { name: 'Salta Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'San Juan',
    options: [
      { name: 'San Juan', correct: true, difficulty: 1 },
      { name: 'Rawson', correct: false, difficulty: 1 },
      { name: 'Chimbas', correct: false, difficulty: 1 },
      { name: 'Caucete', correct: false, difficulty: 1 },
      { name: 'Mendoza', correct: false, difficulty: 2 },
      { name: 'La Rioja', correct: false, difficulty: 2 },
      { name: 'San Luis', correct: false, difficulty: 2 },
      { name: 'San Juan del Norte', correct: false, difficulty: 3 },
      { name: 'San Juan del Sur', correct: false, difficulty: 3 },
      { name: 'Nuevo San Juan', correct: false, difficulty: 3 },
      { name: 'San Juan Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'San Luis',
    options: [
      { name: 'San Luis', correct: true, difficulty: 1 },
      { name: 'Villa Mercedes', correct: false, difficulty: 1 },
      { name: 'Merlo', correct: false, difficulty: 1 },
      { name: 'La Toma', correct: false, difficulty: 1 },
      { name: 'Córdoba', correct: false, difficulty: 2 },
      { name: 'Mendoza', correct: false, difficulty: 2 },
      { name: 'San Juan', correct: false, difficulty: 2 },
      { name: 'San Luis del Norte', correct: false, difficulty: 3 },
      { name: 'San Luis del Sur', correct: false, difficulty: 3 },
      { name: 'Nuevo San Luis', correct: false, difficulty: 3 },
      { name: 'San Luis Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'Santa Cruz',
    options: [
      { name: 'Río Gallegos', correct: true, difficulty: 1 },
      { name: 'Caleta Olivia', correct: false, difficulty: 1 },
      { name: 'El Calafate', correct: false, difficulty: 1 },
      { name: 'Puerto Deseado', correct: false, difficulty: 1 },
      { name: 'Ushuaia', correct: false, difficulty: 2 },
      { name: 'Rawson', correct: false, difficulty: 2 },
      { name: 'Viedma', correct: false, difficulty: 2 },
      { name: 'Río Gallegos del Norte', correct: false, difficulty: 3 },
      { name: 'Río Gallegos del Sur', correct: false, difficulty: 3 },
      { name: 'Nuevo Río Gallegos', correct: false, difficulty: 3 },
      { name: 'Río Gallegos Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'Santa Fe',
    options: [
      { name: 'Santa Fe', correct: true, difficulty: 1 },
      { name: 'Rosario', correct: false, difficulty: 1 },
      { name: 'Rafaela', correct: false, difficulty: 1 },
      { name: 'Venado Tuerto', correct: false, difficulty: 1 },
      { name: 'Paraná', correct: false, difficulty: 2 },
      { name: 'Córdoba', correct: false, difficulty: 2 },
      { name: 'Corrientes', correct: false, difficulty: 2 },
      { name: 'Santa Fe del Norte', correct: false, difficulty: 3 },
      { name: 'Santa Fe del Sur', correct: false, difficulty: 3 },
      { name: 'Nueva Santa Fe', correct: false, difficulty: 3 },
      { name: 'Santa Fe Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'Santiago del Estero',
    options: [
      { name: 'Santiago del Estero', correct: true, difficulty: 1 },
      { name: 'La Banda', correct: false, difficulty: 1 },
      { name: 'Termas de Río Hondo', correct: false, difficulty: 1 },
      { name: 'Frías', correct: false, difficulty: 1 },
      { name: 'San Miguel de Tucumán', correct: false, difficulty: 2 },
      { name: 'Salta', correct: false, difficulty: 2 },
      { name: 'Córdoba', correct: false, difficulty: 2 },
      { name: 'Santiago del Estero del Norte', correct: false, difficulty: 3 },
      { name: 'Santiago del Estero del Sur', correct: false, difficulty: 3 },
      { name: 'Nuevo Santiago del Estero', correct: false, difficulty: 3 },
      { name: 'Santiago del Estero Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'Tierra del Fuego',
    options: [
      { name: 'Ushuaia', correct: true, difficulty: 1 },
      { name: 'Río Grande', correct: false, difficulty: 1 },
      { name: 'Tolhuin', correct: false, difficulty: 1 },
      { name: 'Puerto Almanza', correct: false, difficulty: 1 },
      { name: 'Río Gallegos', correct: false, difficulty: 2 },
      { name: 'Rawson', correct: false, difficulty: 2 },
      { name: 'Viedma', correct: false, difficulty: 2 },
      { name: 'Ushuaia del Norte', correct: false, difficulty: 3 },
      { name: 'Ushuaia del Sur', correct: false, difficulty: 3 },
      { name: 'Nueva Ushuaia', correct: false, difficulty: 3 },
      { name: 'Ushuaia Central', correct: false, difficulty: 3 },
    ],
  },
  {
    province: 'Tucumán',
    options: [
      { name: 'San Miguel de Tucumán', correct: true, difficulty: 1 },
      { name: 'Tafí Viejo', correct: false, difficulty: 1 },
      { name: 'Yerba Buena', correct: false, difficulty: 1 },
      { name: 'Concepción', correct: false, difficulty: 1 },
      { name: 'Santiago del Estero', correct: false, difficulty: 2 },
      { name: 'Salta', correct: false, difficulty: 2 },
      { name: 'San Fernando del Valle de Catamarca', correct: false, difficulty: 2 },
      { name: 'San Miguel de Tucumán del Norte', correct: false, difficulty: 3 },
      { name: 'San Miguel de Tucumán del Sur', correct: false, difficulty: 3 },
      { name: 'Nuevo San Miguel de Tucumán', correct: false, difficulty: 3 },
      { name: 'San Miguel de Tucumán Central', correct: false, difficulty: 3 },
    ],
  },
];
